[package]
name = "IDS721_PROJ2_COURSERA"
version = "0.1.0"
edition = "2018"

[dependencies]
ndarray = "0.15.4"
ndarray-stats = "0.4.0"
ndarray-linalg = "0.14.0"
csv = "1.1.6"
rust_tokenizers = "8.0.0"
